# Generated by Django 3.2 on 2022-01-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentRollNumber', models.CharField(max_length=20)),
                ('StudentName', models.CharField(max_length=50)),
                ('StudentClass', models.CharField(max_length=50, null=True)),
                ('StudentSchool', models.CharField(max_length=50, null=True)),
                ('StudentMobile', models.IntegerField(null=True)),
                ('StudentAddress', models.CharField(max_length=50, null=True)),
                ('MathMarks', models.IntegerField(null=True)),
                ('PhysicsMarks', models.IntegerField(null=True)),
                ('ChemistryMarks', models.IntegerField(null=True)),
                ('BioMarks', models.IntegerField(null=True)),
                ('EnglishMarks', models.IntegerField(null=True)),
            ],
        ),
    ]
