# Generated by Django 3.2 on 2022-01-20 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='StudentMobile',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
